import * as XLSX from 'xlsx';

export const XLSX_MIME = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';

export type ExportCell = string | number | boolean | Date | null | undefined;
export type ExportRow = Record<string, ExportCell>;

export function safeFilename(value: string): string {
  const safe = value.replace(/[^A-Za-z0-9._-]+/g, '_').replace(/_+/g, '_').replace(/^[_\.]+|[_\.]+$/g, '');
  return `${safe || 'REP_TRACK_Export'}.xlsx`;
}

export function dedupeById<T extends { id: string }>(rows: T[]): T[] {
  return [...new Map(rows.map((row) => [row.id, row])).values()];
}

export function createWorkbook(sheets: Array<{ name: string; rows: ExportRow[] }>): Uint8Array {
  const workbook = XLSX.utils.book_new();
  for (const { name, rows } of sheets) {
    const worksheet = XLSX.utils.json_to_sheet(rows.length ? rows : [{ Message: 'No records for the selected filters' }], {
      cellDates: true,
    });
    const headers = rows.length ? Object.keys(rows[0]) : ['Message'];
    worksheet['!cols'] = headers.map((header) => ({ wch: Math.min(42, Math.max(12, header.length + 2)) }));
    worksheet['!autofilter'] = worksheet['!ref'] ? { ref: worksheet['!ref'] } : undefined;
    worksheet['!freeze'] = { xSplit: 0, ySplit: 1, topLeftCell: 'A2', activePane: 'bottomLeft', state: 'frozen' };
    worksheet['!pageSetup'] = { orientation: 'landscape', fitToWidth: 1, fitToHeight: 0 };
    worksheet['!margins'] = { left: 0.25, right: 0.25, top: 0.5, bottom: 0.5, header: 0.2, footer: 0.2 };
    for (const cell of Object.values(worksheet)) if (cell && typeof cell === 'object' && 'v' in cell) {
      const target=cell as XLSX.CellObject; if(target.v==='Available') target.s={fill:{fgColor:{rgb:'C6EFCE'}},font:{color:{rgb:'006100'},bold:true}}; if(target.v==='Not Available') target.s={fill:{fgColor:{rgb:'FFC7CE'}},font:{color:{rgb:'9C0006'},bold:true}};
    }
    XLSX.utils.book_append_sheet(workbook, worksheet, name.slice(0, 31));
  }
  return XLSX.write(workbook, { type: 'buffer', bookType: 'xlsx', compression: true, cellStyles: true }) as Uint8Array;
}

export function workbookResponse(bytes: Uint8Array, requestedFilename: string): Response {
  const filename = safeFilename(requestedFilename.replace(/\.xlsx$/i, ''));
  return new Response(Buffer.from(bytes), {
    status: 200,
    headers: {
      'Content-Type': XLSX_MIME,
      'Content-Disposition': `attachment; filename="${filename}"`,
      'Cache-Control': 'private, no-store',
      'X-Content-Type-Options': 'nosniff',
    },
  });
}

export function metadataRows(session: { name: string; positionCode?: string | null }, context: Record<string, string | undefined>): ExportRow[] {
  return [
    { Field: 'Generated At', Value: new Date().toISOString() },
    { Field: 'Generated By', Value: session.name },
    { Field: 'Position', Value: session.positionCode ?? '' },
    ...Object.entries(context).filter(([, value]) => value).map(([key, value]) => ({ Field: key, Value: value ?? '' })),
  ];
}
