import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import * as XLSX from 'xlsx';import {PRODUCTS_LIST,OUR_PRODUCTS_DISCUSSED_LIST,SUNNY_PRODUCTS_LIST}from'../src/lib/constants';import{HospitalDailyReportSchema,MasterHospitalSchema,MasterDoctorSchema,MasterPharmacySchema,ProductAvailabilityBatchSchema}from'../src/lib/validation';import{createWorkbook}from'../src/lib/exportWorkbook';
export function runTask1Tests(){let passed=0,failed=0;const test=(name:string,fn:()=>void)=>{try{fn();passed++;console.log(`  ✓ ${name}`)}catch(e){failed++;console.error(`  ✗ ${name}`,e)}};console.log('\n🧪 Running Task 1 MR workflow tests...');
 test('canonical catalog reconciles to the 86 unique products supplied by the business',()=>{assert.equal(PRODUCTS_LIST.length,86);assert.equal(new Set(PRODUCTS_LIST).size,86);assert.equal(OUR_PRODUCTS_DISCUSSED_LIST.length,4);assert.equal(SUNNY_PRODUCTS_LIST,PRODUCTS_LIST);assert.ok(!PRODUCTS_LIST.some(x=>x.startsWith('Todosunny')))});
 test('hospital multi-types validate and removed contacts are stripped',()=>{const x=MasterHospitalSchema.parse({name:'H',hospitalTypes:['Private','University'],keyPersonPhone:'01001234567'});assert.deepEqual(x.hospitalTypes,['Private','University']);assert.equal('keyPersonPhone'in x,false)});
 test('doctor removed fields are stripped and nearby pharmacies validate',()=>{const x=MasterDoctorSchema.parse({name:'Dr',workingHospitalIds:['h1'],nearbyPharmacyIds:['p1'],code:'legacy'});assert.equal('code'in x,false);assert.equal('workingHospitalIds'in x,false);assert.deepEqual(x.nearbyPharmacyIds,['p1'])});
 test('pharmacy distributors validate and Others requires explanation',()=>{assert.equal(MasterPharmacySchema.safeParse({name:'P',distributors:['OTHERS']}).success,false);const x=MasterPharmacySchema.parse({name:'P',distributors:['ETO','OTHERS'],distributorOther:'Local'});assert.deepEqual(x.distributors,['ETO','OTHERS'])});
 test('unlimited hospital department and doctor collections validate',()=>{const visits=Array.from({length:12},(_,i)=>({hospitalId:`h${i}`,departments:[{department:'ICU',doctors:Array.from({length:9},(_,j)=>`Doctor ${j}`)}]}));assert.equal(HospitalDailyReportSchema.parse({reportDate:'2026-09-12',visits}).visits.length,12)});
 test('availability rejects duplicate product items',()=>{assert.equal(ProductAvailabilityBatchSchema.safeParse({hospitalId:'h',month:'2026-09',items:[{productId:'p',status:'Available'},{productId:'p',status:'Not Available'}]}).success,false)});
 test('availability workbook opens with detail and matrix sheets',()=>{const bytes=createWorkbook([{name:'Availability Detail',rows:[{Hospital:'H',Product:'P','Availability Status':'Available'}]},{name:'Hospital Matrix',rows:[{Hospital:'H',P:'Not Available'}]}]);const book=XLSX.read(bytes);assert.deepEqual(book.SheetNames,['Availability Detail','Hospital Matrix'])});
 test('MR UI has separate availability navigation and no report-picker entry',()=>{const root=process.cwd();const workspace=fs.readFileSync(path.join(root,'src/components/workspace/MedicalRepWorkspace.tsx'),'utf8');const picker=fs.readFileSync(path.join(root,'src/components/reports/TypePicker.tsx'),'utf8');assert.match(workspace,/activeView === 'availability'/);assert.doesNotMatch(picker,/targetType:\s*'availability'/)});
 test('MR list UI contains no editable daily-rate or Doctor Code controls',()=>{const root=process.cwd();const lists=fs.readFileSync(path.join(root,'src/components/my-lists/MyListsView.tsx'),'utf8');const doctor=fs.readFileSync(path.join(root,'src/components/reports/DoctorForm.tsx'),'utf8');assert.doesNotMatch(lists,/handleDailyInputChange/);assert.doesNotMatch(doctor,/id="code"/)});return{passed,failed}}
