import assert from 'node:assert/strict';import fs from 'node:fs';import {submissionWindowOpen,BUSINESS_TIME_ZONE} from '../src/lib/business/reportDeadline';import {WeeklyPlanSchema,ManagerActivitySchema} from '../src/lib/validation';
export function runTask4Tests(){let passed=0,failed=0;const t=(name:string,fn:()=>void)=>{try{fn();passed++;console.log('  ✓ '+name)}catch(e){failed++;console.error('  ✗ '+name,e)}};console.log('\nTASK 4 tests');
 t('Cairo deadline accepts before 09:00 and rejects at/after',()=>{assert.equal(BUSINESS_TIME_ZONE,'Africa/Cairo');assert.equal(submissionWindowOpen('2026-09-14',new Date('2026-09-15T05:59:59Z')),true);assert.equal(submissionWindowOpen('2026-09-14',new Date('2026-09-15T06:00:00Z')),false);assert.equal(submissionWindowOpen('2026-09-14',new Date('2026-09-15T08:00:00Z')),false)});
 t('structured plan validates descriptions and AM/PM structure',()=>{const c={hospitalIds:[],branchIds:[],doctorIds:[],pharmacyIds:[],activities:['OTHERS'],salesReviewDescription:'',othersDescription:''};assert.throws(()=>WeeklyPlanSchema.parse({startDate:'2026-09-19',endDate:'2026-09-25',structuredPlan:{saturday:{am:c,pm:{...c,activities:[],othersDescription:''}}}}));});
 t('manager report requires selected MR',()=>assert.throws(()=>ManagerActivitySchema.parse({activityType:'Visit',activityDate:'2026-09-15',visits:[]})));
 t('Sales Performance UI and routes are removed',()=>{assert.equal(fs.existsSync('src/components/sales/SalesAnalyticsView.tsx'),false);assert.equal(fs.existsSync('src/app/api/sales/analytics/route.ts'),false);assert.doesNotMatch(fs.readFileSync('src/components/workspace/MedicalRepWorkspace.tsx','utf8'),/SalesAnalyticsView|Sales performance/)});
 t('Rafik override is stable-ID migration and rebuilds paths',()=>{const s=fs.readFileSync('scripts/migrate_task4.ts','utf8');assert.match(s,/rafik\.id,osama\.id/);assert.match(s,/computeTransitiveClosure/);assert.match(s,/is_active=0/)});
 t('coverage is server-authorized and unique-day cycle based',()=>{const s=fs.readFileSync('src/lib/services/coverageService.ts','utf8');assert.match(s,/assertRepVisible/);assert.match(s,/COUNT\(DISTINCT/);assert.match(s,/default_cycle/)});
 return{passed,failed}}
