import assert from 'node:assert/strict';import fs from 'node:fs';import {ManagerActivitySchema} from '../src/lib/validation';
export function runTask5Tests(){let passed=0,failed=0;const t=(name:string,fn:()=>void)=>{try{fn();passed++;console.log(`  ✓ ${name}`)}catch(e){failed++;console.error(`  ✗ ${name}`,e)}};console.log('\nFINAL backend tests');
 const manual={name:'Vacant Hospital',hospitalType:'Private',area:'Cairo',address:'Street',specialty:'',distributor:'',products:[]};
 t('Vacant accepts null MR and manual AM/PM entries',()=>assert.equal(ManagerActivitySchema.safeParse({reportContextType:'VACANT',selectedRepId:null,activityType:'Visit',activityDate:'2026-09-16',visits:[{period:'AM',entryType:'HOSPITAL',manualData:manual,doctors:[{doctorName:'Dr One',department:'Cardiology'}]},{period:'PM',entryType:'DIRECT_DOCTOR',manualData:{...manual,name:'Dr Two',specialty:'Oncology'},doctors:[]}]}).success,true));
 t('Vacant rejects employee IDs and list-only entities',()=>{assert.equal(ManagerActivitySchema.safeParse({reportContextType:'VACANT',selectedRepId:'rep-1',activityType:'Visit',activityDate:'2026-09-16'}).success,false);assert.equal(ManagerActivitySchema.safeParse({reportContextType:'VACANT',activityType:'Visit',activityDate:'2026-09-16',visits:[{period:'AM',entryType:'HOSPITAL',hospitalId:'h1'}]}).success,false)});
 t('Employee context still requires an authorized MR',()=>assert.equal(ManagerActivitySchema.safeParse({reportContextType:'EMPLOYEE',activityType:'Visit',activityDate:'2026-09-16'}).success,false));
 t('Vacant migration is additive and contains no fake user',()=>{const s=fs.readFileSync('scripts/migrations/task5_vacant_context.sql','utf8');assert.match(s,/report_context_type/);assert.doesNotMatch(s,/INSERT INTO users|DROP TABLE|DELETE FROM/) });
 t('UI offers final Vacant option and manual entity forms',()=>{const s=fs.readFileSync('src/components/manager/ManagerActivityForm.tsx','utf8');assert.match(s,/<option value="__VACANT__">Vacant<\/option>/);for(const x of ['Hospital type','Specialty','Distributor dealt with','Distributed products and observations'])assert.match(s,new RegExp(x))});
 t('Product Analysis operational surfaces are retired',()=>{const files=['src/app/page.tsx','src/components/workspace/ManagerWorkspace.tsx','src/components/compliance/ComplianceView.tsx','src/components/exports/ExportCenter.tsx'].map(x=>fs.readFileSync(x,'utf8')).join('\n');assert.doesNotMatch(files,/Product Analysis|Monthly Product Analysis/);assert.equal(fs.existsSync('src/lib/services/salesAnalyticsService.ts'),false)});
 return{passed,failed}}
