import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import * as XLSX from 'xlsx';import {PRODUCTS_LIST,OUR_PRODUCTS_DISCUSSED_LIST,SUNNY_PRODUCTS_LIST}from'../src/lib/constants';import{HospitalDailyReportSchema,MasterHospitalSchema,MasterDoctorSchema,MasterPharmacySchema,ProductAvailabilityBatchSchema}from'../src/lib/validation';import{createWorkbook}from'../src/lib/exportWorkbook';
export function runTask1Tests(){let passed=0,failed=0;const test=(name:string,fn:()=>void)=>{try{fn();passed++;console.log(`  ✓ ${name}`)}catch(e){failed++;console.error(`  ✗ ${name}`,e)}};console.log('\n🧪 Running Task 1 MR workflow tests...');
 test('canonical catalog has exactly 78 unique products',()=>{assert.equal(PRODUCTS_LIST.length,78);assert.equal(new Set(PRODUCTS_LIST).size,78);assert.equal(OUR_PRODUCTS_DISCUSSED_LIST,PRODUCTS_LIST);assert.equal(SUNNY_PRODUCTS_LIST,PRODUCTS_LIST)});
 test('hospital multi-types and string phones validate',()=>{const x=MasterHospitalSchema.parse({name:'H',hospitalTypes:['Private','University'],keyPersonPhone:'01001234567',purchasingContactPhone:'+201001234567'});assert.deepEqual(x.hospitalTypes,['Private','University']);assert.equal(x.keyPersonPhone,'01001234567')});
 test('doctor code is not accepted as a modeled field and relationships validate',()=>{const x=MasterDoctorSchema.parse({name:'Dr',workingHospitalIds:['h1'],nearbyPharmacyIds:['p1'],code:'legacy'});assert.equal('code'in x,false);assert.deepEqual(x.workingHospitalIds,['h1'])});
 test('pharmacy product list is not accepted as a modeled field',()=>{const x=MasterPharmacySchema.parse({name:'P',targetProducts:'obsolete'});assert.equal('targetProducts'in x,false)});
 test('unlimited hospital and nested doctor collections validate',()=>{const visits=Array.from({length:12},(_,i)=>({hospitalId:`h${i}`,objective:'Routine',doctors:Array.from({length:9},(_,j)=>({doctorId:`d${j}`}))}));assert.equal(HospitalDailyReportSchema.parse({reportDate:'2026-09-12',visits}).visits.length,12)});
 test('Others requires explanation',()=>{assert.equal(HospitalDailyReportSchema.safeParse({reportDate:'2026-09-12',visits:[{hospitalId:'h',objective:'Others: ',doctors:[]}]}).success,false)});
 test('availability rejects duplicate product items',()=>{assert.equal(ProductAvailabilityBatchSchema.safeParse({hospitalId:'h',month:'2026-09',items:[{productId:'p',status:'Available'},{productId:'p',status:'Not Available'}]}).success,false)});
 test('availability workbook opens with detail and matrix sheets',()=>{const bytes=createWorkbook([{name:'Availability Detail',rows:[{Hospital:'H',Product:'P','Availability Status':'Available'}]},{name:'Hospital Matrix',rows:[{Hospital:'H',P:'Not Available'}]}]);const book=XLSX.read(bytes);assert.deepEqual(book.SheetNames,['Availability Detail','Hospital Matrix'])});
 test('MR UI has separate availability navigation and no report-picker entry',()=>{const root=process.cwd();const workspace=fs.readFileSync(path.join(root,'src/components/workspace/MedicalRepWorkspace.tsx'),'utf8');const picker=fs.readFileSync(path.join(root,'src/components/reports/TypePicker.tsx'),'utf8');assert.match(workspace,/activeView === 'availability'/);assert.doesNotMatch(picker,/targetType:\s*'availability'/)});
 test('MR list UI contains no editable daily-rate or Doctor Code controls',()=>{const root=process.cwd();const lists=fs.readFileSync(path.join(root,'src/components/my-lists/MyListsView.tsx'),'utf8');const doctor=fs.readFileSync(path.join(root,'src/components/reports/DoctorForm.tsx'),'utf8');assert.doesNotMatch(lists,/handleDailyInputChange/);assert.doesNotMatch(doctor,/id="code"/)});return{passed,failed}}
