import assert from 'node:assert/strict';import fs from 'node:fs';import * as XLSX from 'xlsx';import {ManagerActivitySchema}from'../src/lib/validation';import{createWorkbook}from'../src/lib/exportWorkbook';import{resolveHierarchyUserIds}from'../src/lib/services/hierarchyService';
export function runTask2Tests(){let passed=0,failed=0;const test=(name:string,fn:()=>void)=>{try{fn();passed++;console.log(`  ✓ ${name}`)}catch(e){failed++;console.error(`  ✗ ${name}`,e)}};console.log('\n🧪 Running Task 2 Manager workflow tests...');
test('AM/PM relational visits support unlimited hospitals and doctors',()=>{const visits=Array.from({length:24},(_,i)=>({period:i%2?'PM':'AM',entryType:'HOSPITAL',hospitalId:`h${i}`,generalComment:'hospital',doctors:Array.from({length:12},(_,j)=>({doctorId:`d${j}`,generalComment:'doctor'}))}));assert.equal(ManagerActivitySchema.parse({activityType:'Visit',activityDate:'2026-09-13',visits}).visits.length,24)});
test('event feedback length is validated and products use stable IDs',()=>{const value=ManagerActivitySchema.parse({activityType:'Event',activityDate:'2026-09-13',eventName:'E',eventFeedback:'Useful feedback',productIds:['p1','p2']});assert.deepEqual(value.productIds,['p1','p2']);assert.equal(ManagerActivitySchema.safeParse({...value,eventFeedback:'x'.repeat(5001)}).success,false)});
test('manager activity UI replaces Morning/Afternoon with AM/PM repeaters',()=>{const ui=fs.readFileSync('src/components/manager/ManagerActivityForm.tsx','utf8');assert.match(ui,/\['AM','PM'\]/);assert.match(ui,/Add hospital visit/);assert.match(ui,/Add doctor visit/);assert.doesNotMatch(ui,/Morning|Afternoon/)});
test('sales analytics is removed from manager workspace and availability replaces it',()=>{const ui=fs.readFileSync('src/components/workspace/ManagerWorkspace.tsx','utf8');assert.doesNotMatch(ui,/SalesAnalyticsView/);assert.match(ui,/Product Availability/)});
test('manager availability has explicit hierarchy and record filters',()=>{const ui=fs.readFileSync('src/components/manager/ManagerAvailabilityView.tsx','utf8');for(const term of ['DIRECT_REPORTS','ALL_DESCENDANTS','Hospital','Area / Territory','Product','Status'])assert.match(ui,new RegExp(term))});
test('skipped-level hierarchy and unrelated denial remain correct',()=>{const active=new Set(['mr','dm','bum','smd','peer']);const edges=[{subordinateUserId:'mr',managerUserId:'dm'},{subordinateUserId:'dm',managerUserId:'bum'},{subordinateUserId:'bum',managerUserId:'smd'}];assert.deepEqual(resolveHierarchyUserIds('smd',edges,active,'ALL_DESCENDANTS'),['bum','dm','mr']);assert.deepEqual(resolveHierarchyUserIds('peer',edges,active,'ALL_DESCENDANTS'),[])});
test('availability workbook opens with detail matrix summary and status colors enabled',()=>{const bytes=createWorkbook([{name:'Detailed Availability',rows:[{Status:'Available'}]},{name:'Hospital Product Matrix',rows:[{Hospital:'H',P:'Not Available'}]},{name:'Summary',rows:[{Available:1}]}]);const book=XLSX.read(bytes,{cellStyles:true});assert.deepEqual(book.SheetNames,['Detailed Availability','Hospital Product Matrix','Summary']);assert.ok(book.Sheets['Detailed Availability']['!autofilter'])});
test('Task 2 migration is additive and legacy columns remain',()=>{const sql=fs.readFileSync('scripts/migrations/task2_manager_workflow.sql','utf8');assert.doesNotMatch(sql,/DROP TABLE|TRUNCATE|DELETE FROM/i);const schema=fs.readFileSync('src/lib/db/schema.ts','utf8');assert.match(schema,/morningHospitalName/);assert.match(schema,/managerActivityEntries/)});return{passed,failed}}
