import assert from 'node:assert/strict';import fs from 'node:fs';import {BUSINESS_PRODUCT_OPTIONS,HOSPITAL_DEPARTMENTS,PRODUCTS_LIST}from'../src/lib/constants';import{BranchVisitV3Schema,DoctorVisitV3Schema,MasterDoctorSchema,MasterHospitalSchema,MasterPharmacySchema,PharmacyVisitV3Schema,SpecialTaskSchema,TrainingSchema}from'../src/lib/validation';
export function runTask3Tests(){let passed=0,failed=0;const test=(name:string,fn:()=>void)=>{try{fn();passed++;console.log(`  ✓ ${name}`)}catch(error){failed++;console.error(`  ✗ ${name}`,error)}};console.log('\n🧪 Running Task 3 tests...');
test('catalog additions active and Todosunny excluded',()=>{for(const name of ['Levosimendan Sunny','Lodosunny','Sunnyprixat'])assert.ok(PRODUCTS_LIST.includes(name));assert.equal(PRODUCTS_LIST.some(x=>/todosunny/i.test(x)),false);assert.equal(new Set(PRODUCTS_LIST.map(x=>x.trim().toLowerCase())).size,PRODUCTS_LIST.length)});
test('four-product subset maps to canonical products',()=>{assert.deepEqual(BUSINESS_PRODUCT_OPTIONS.map(x=>x.label),['Nitron','Danasetron','Beconeurin','Levosimendan Sunny']);for(const x of BUSINESS_PRODUCT_OPTIONS)assert.ok(PRODUCTS_LIST.includes(x.canonicalName))});
test('removed master fields are stripped',()=>{assert.equal('keyPersonName'in MasterHospitalSchema.parse({name:'H'}),false);assert.equal('mobile'in MasterDoctorSchema.parse({name:'D'}),false);assert.equal('pharmacist'in MasterPharmacySchema.parse({name:'P',distributors:['ETO']}),false)});
test('pharmacy distributor normalization and Others rule',()=>{assert.equal(MasterPharmacySchema.safeParse({name:'P',distributors:['OTHERS']}).success,false);assert.equal(MasterPharmacySchema.safeParse({name:'P',distributors:['PHARMAOVERSEAS','DIRECT','OTHERS'],distributorOther:'Local'}).success,true)});
test('all hospital departments are present',()=>assert.deepEqual(HOSPITAL_DEPARTMENTS,['ICU','CCU','Cardio','Anaesthesia','IM','Pedia','Onco','Neuro','Neuro ICU','Gyna','Cardiosurgery','Emergency','Nephro']));
test('product-specific payloads reject empty selections',()=>{assert.equal(DoctorVisitV3Schema.safeParse({doctorId:'d',products:[]}).success,false);assert.equal(PharmacyVisitV3Schema.safeParse({pharmacyId:'p',productIds:[]}).success,false);assert.equal(BranchVisitV3Schema.safeParse({branchId:'b',products:[]}).success,false)});
test('training and admin work accept only simplified active fields',()=>{const training=TrainingSchema.parse({title:'T',trainingDate:'2026-09-15',trainingType:'old',location:'Cairo'});assert.equal('trainingType'in training,false);const task=SpecialTaskSchema.parse({title:'Review',description:'Done',taskCategory:'old'});assert.equal('taskCategory'in task,false)});
test('forms omit obsolete controls and preserve required product UI',()=>{const read=(x:string)=>fs.readFileSync(x,'utf8');const hospital=read('src/components/reports/HospitalForm.tsx'),pharmacy=read('src/components/reports/PharmacyForm.tsx'),doctor=read('src/components/reports/DoctorForm.tsx'),branch=read('src/components/reports/BranchForm.tsx'),event=read('src/components/reports/EventForm.tsx');for(const value of ['VisitObjectiveSelect','Visit cycle days','Next visit','Competitor','Visit notes'])assert.doesNotMatch(hospital,new RegExp(value,'i'));assert.match(hospital,/Add Doctor/);assert.doesNotMatch(pharmacy,/VisitObjectiveSelect/);assert.match(doctor,/Prescription Rate/);assert.match(branch,/Notes and Observations/);assert.doesNotMatch(event,/OUR_PRODUCTS_DISCUSSED_LIST/)});
test('availability starts with no automatic status',()=>{const availability=fs.readFileSync('src/components/reports/AvailabilityForm.tsx','utf8');assert.match(availability,/setStatuses\(\{\}\)/);assert.doesNotMatch(availability,/map\(\(p:Product\)=>\[p.id,'Available'\]\)/)});
return{passed,failed}}
