-- Task 1 additive-only migration. Apply once after inspecting/backup of production D1.
ALTER TABLE hospitals ADD COLUMN hospital_types TEXT NOT NULL DEFAULT '[]';
ALTER TABLE hospitals ADD COLUMN address TEXT;
ALTER TABLE hospitals ADD COLUMN key_person_name TEXT;
ALTER TABLE hospitals ADD COLUMN key_person_phone TEXT;
ALTER TABLE hospitals ADD COLUMN purchasing_contact_name TEXT;
ALTER TABLE hospitals ADD COLUMN purchasing_contact_phone TEXT;
ALTER TABLE doctors ADD COLUMN clinic_address TEXT;
ALTER TABLE hospital_visits ADD COLUMN objective_other_text TEXT;
CREATE TABLE IF NOT EXISTS daily_reports (id TEXT PRIMARY KEY NOT NULL, rep_id TEXT NOT NULL REFERENCES representatives(id) ON DELETE RESTRICT, report_date TEXT NOT NULL, submitted_at INTEGER NOT NULL DEFAULT (unixepoch() * 1000), updated_at INTEGER NOT NULL DEFAULT (unixepoch() * 1000));
ALTER TABLE hospital_visits ADD COLUMN daily_report_id TEXT REFERENCES daily_reports(id) ON DELETE CASCADE;
CREATE TABLE IF NOT EXISTS hospital_visit_doctors (id TEXT PRIMARY KEY NOT NULL, hospital_visit_id TEXT NOT NULL REFERENCES hospital_visits(id) ON DELETE CASCADE, doctor_id TEXT NOT NULL REFERENCES doctors(id) ON DELETE RESTRICT, specialty_snapshot TEXT, comment TEXT);
ALTER TABLE pharmacy_visits ADD COLUMN objective_other_text TEXT;
ALTER TABLE doctor_visits ADD COLUMN objective_other_text TEXT;
ALTER TABLE branch_visits ADD COLUMN objective_other_text TEXT;
CREATE TABLE IF NOT EXISTS doctor_working_hospitals (doctor_id TEXT NOT NULL REFERENCES doctors(id) ON DELETE CASCADE, hospital_id TEXT NOT NULL REFERENCES hospitals(id) ON DELETE CASCADE, UNIQUE (doctor_id, hospital_id));
CREATE TABLE IF NOT EXISTS doctor_nearby_pharmacies (doctor_id TEXT NOT NULL REFERENCES doctors(id) ON DELETE CASCADE, pharmacy_id TEXT NOT NULL REFERENCES pharmacies(id) ON DELETE CASCADE, UNIQUE (doctor_id, pharmacy_id));
CREATE TABLE IF NOT EXISTS representative_visit_rates (id TEXT PRIMARY KEY NOT NULL, rep_id TEXT NOT NULL REFERENCES representatives(id) ON DELETE CASCADE, customer_category TEXT NOT NULL CHECK(customer_category IN ('HOSPITAL','DOCTOR','PHARMACY','DISTRIBUTION_BRANCH')), daily_rate INTEGER NOT NULL DEFAULT 0 CHECK(daily_rate >= 0), working_days_per_week INTEGER NOT NULL DEFAULT 6 CHECK(working_days_per_week > 0), working_days_per_month INTEGER NOT NULL DEFAULT 26 CHECK(working_days_per_month > 0), effective_from TEXT NOT NULL, effective_to TEXT, created_at INTEGER NOT NULL DEFAULT (unixepoch() * 1000), updated_at INTEGER NOT NULL DEFAULT (unixepoch() * 1000), UNIQUE (rep_id, customer_category, effective_from));
CREATE INDEX IF NOT EXISTS idx_rep_visit_rate_rep ON representative_visit_rates(rep_id);
UPDATE hospitals SET hospital_types = json_array(type) WHERE hospital_types = '[]' AND type IS NOT NULL AND trim(type) <> '';
