'use client';
import { useEffect, useState } from 'react'; import { KeyRound, ShieldCheck, UserCheck, UserRoundX, Users } from 'lucide-react';
import { SectionCard } from '@/components/ui/SectionCard'; import { Skeleton } from '@/components/ui/Skeleton'; import { InlineAlert } from '@/components/ui/InlineAlert'; import { EmptyState } from '@/components/ui/EmptyState'; import { useTranslation } from '@/lib/i18nContext'; import type { AuditRow } from './adminTypes'; import { dateText } from './adminTypes';
type Overview = { active:number; inactive:number; mustChange:number; mr:number; managers:number; vacantAssignments:number; recentActions:AuditRow[] };
export function AdminOverview() { const { language } = useTranslation(); const ar=language==='ar'; const [data,setData]=useState<Overview|null>(null); const [error,setError]=useState('');
  useEffect(()=>{ const controller=new AbortController(); fetch('/api/admin/overview',{signal:controller.signal}).then(async r=>{if(!r.ok)throw new Error((await r.json()).message);return r.json();}).then(x=>setData(x.overview)).catch(e=>{if(e.name!=='AbortError')setError(e.message);}); return()=>controller.abort();},[]);
  if(error)return <InlineAlert tone="error">{error}</InlineAlert>; if(!data)return <Skeleton className="h-80"/>;
  const cards=[['Active users',data.active,UserCheck],['Inactive users',data.inactive,UserRoundX],['Password change required',data.mustChange,KeyRound],['MR users',data.mr,Users],['Manager users',data.managers,ShieldCheck],['Vacant assignments',data.vacantAssignments,Users]] as const;
  return <div className="space-y-5"><header><p className="text-sm font-semibold text-[var(--gold-dark)]">{ar?'عمليات آمنة':'Secure operations'}</p><h1 className="text-2xl font-black">{ar?'نظرة عامة للإدارة':'Admin overview'}</h1></header><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{cards.map(([label,value,Icon])=><SectionCard key={label}><Icon className="mb-3 size-5 text-[var(--gold-dark)]"/><p className="text-3xl font-black">{value ?? 0}</p><p className="text-sm text-[var(--ink-soft)]">{label}</p></SectionCard>)}</div><SectionCard title={ar?'أحدث إجراءات الأمان':'Recent security actions'}>{data.recentActions.length?<div className="divide-y divide-[var(--line)]">{data.recentActions.map(row=><div className="flex flex-wrap justify-between gap-2 py-3 text-sm" key={row.id}><span className="font-semibold">{row.actionType.replaceAll('_',' ')}</span><span className="font-mono text-xs text-[var(--ink-soft)]">{dateText(row.createdAt)}</span></div>)}</div>:<EmptyState title={ar?'لا توجد إجراءات مسجلة':'No security actions recorded'}/>}</SectionCard></div>;
}
