'use client';
import { useState } from 'react';
import { Download, FileSpreadsheet, CalendarDays, BarChart3, ListChecks, ShieldCheck } from 'lucide-react';
import { useTranslation } from '@/lib/i18nContext';
import type { Representative } from '@/types';
import { Button } from '@/components/ui/Button';
import { InlineAlert } from '@/components/ui/InlineAlert';
import { SectionCard } from '@/components/ui/SectionCard';

type Props={manager?:boolean;reps:Representative[]};
const today=()=>new Date().toISOString().slice(0,10);
const monthNow=()=>today().slice(0,7);
const saturday=()=>{const d=new Date();d.setDate(d.getDate()-((d.getDay()+1)%7));return d.toISOString().slice(0,10)};

export function ExportCenter({manager=false,reps}:Props){
  const{language}=useTranslation();const ar=language==='ar';
  const[scope,setScope]=useState('ALL_DESCENDANTS');const[startDate,setStartDate]=useState('');const[endDate,setEndDate]=useState('');const[weekStart,setWeekStart]=useState(saturday());const[month,setMonth]=useState(monthNow());const[reportType,setReportType]=useState('all');const[complianceType,setComplianceType]=useState('DAILY_REPORT');const[repId,setRepId]=useState('');const[busy,setBusy]=useState('');const[error,setError]=useState('');
  const l=(en:string,a:string)=>ar?a:en;
  async function download(key:string,url:string){if(busy)return;setBusy(key);setError('');try{const response=await fetch(url,{credentials:'same-origin'});if(!response.ok){const body=await response.json().catch(()=>null);throw new Error(body?.message||l('Unable to generate export','تعذر إنشاء ملف التصدير'))}const blob=await response.blob();const disposition=response.headers.get('content-disposition')||'';const filename=disposition.match(/filename="([^"]+)"/)?.[1]||'REP_TRACK_Export.xlsx';const objectUrl=URL.createObjectURL(blob);const a=document.createElement('a');a.href=objectUrl;a.download=filename;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(objectUrl)}catch(e){setError(e instanceof Error?e.message:l('Export failed','فشل التصدير'))}finally{setBusy('')}}
  const scopeQuery=manager?`scopeMode=${scope}`:'';
  const cards=[
    {key:'reports',icon:<FileSpreadsheet className="size-5"/>,title:l(manager?'Team Reports':'My Reports',manager?'تقارير الفريق':'تقاريري'),desc:l('Visits, events, training, special tasks and availability in clear worksheets.','الزيارات والفعاليات والتدريب والمهام الخاصة والتوافر في أوراق واضحة.'),url:`/api/exports/reports?owner=${manager?'team':'my'}&${scopeQuery}${scopeQuery?'&':''}type=${reportType}${startDate?`&startDate=${startDate}`:''}${endDate?`&endDate=${endDate}`:''}${repId?`&repId=${encodeURIComponent(repId)}`:''}`},
    {key:'plans',icon:<CalendarDays className="size-5"/>,title:l(manager?'Team Weekly Plans':'My Weekly Plans',manager?'خطط الفريق الأسبوعية':'خططي الأسبوعية'),desc:l('Saturday–Friday plans for the selected authorized scope.','خطط السبت إلى الجمعة للنطاق المصرح المحدد.'),url:`/api/exports/weekly-plans?team=${manager?'true':'false'}&${scopeQuery}${scopeQuery?'&':''}weekStart=${weekStart}${repId?`&repId=${encodeURIComponent(repId)}`:''}`},
    {key:'sales',icon:<BarChart3 className="size-5"/>,title:l('Sales Analytics','تحليلات المبيعات'),desc:l('Monthly and YTD summaries using the same Product Analysis calculations.','ملخصات شهرية وتراكمية بنفس حسابات تحليل المنتجات.'),url:`/api/exports/sales?month=${month}&scope=${scope==='DIRECT_REPORTS'?'direct':'all'}`},
    {key:'lists',icon:<ListChecks className="size-5"/>,title:l(manager?'Team Lists':'My Lists',manager?'قوائم الفريق':'قوائمي'),desc:l(manager?'Select a representative to export persisted customer lists.':'Hospitals, doctors, pharmacies and distribution branches.','اختر مندوباً لتصدير قوائم العملاء المحفوظة.'),url:`/api/exports/lists${repId?`?repId=${encodeURIComponent(repId)}`:''}`},
    ...(manager?[{key:'my-reports',icon:<FileSpreadsheet className="size-5"/>,title:l('My Manager Activities','أنشطتي الإدارية'),desc:l('Your own manager activity records only.','سجلات أنشطتك الإدارية فقط.'),url:`/api/exports/reports?owner=my&type=managerActivity${startDate?`&startDate=${startDate}`:''}${endDate?`&endDate=${endDate}`:''}`},{key:'my-plans',icon:<CalendarDays className="size-5"/>,title:l('My Weekly Plans','خططي الأسبوعية'),desc:l('Your own manager weekly plans.','خططك الأسبوعية الشخصية.'),url:`/api/exports/weekly-plans?team=false&weekStart=${weekStart}`},{key:'compliance',icon:<ShieldCheck className="size-5"/>,title:l('Submission Compliance','الالتزام بالتقديم'),desc:l('Daily reports, weekly plans, or monthly analysis compliance.','التزام التقارير اليومية أو الخطط الأسبوعية أو التحليل الشهري.'),url:`/api/exports/compliance?type=${complianceType}&${scopeQuery}&${complianceType==='DAILY_REPORT'?`date=${startDate||today()}`:complianceType==='WEEKLY_PLAN'?`weekStart=${weekStart}`:`month=${month}`}`}]:[]),
  ];
  return <div className="space-y-5" dir={ar?'rtl':'ltr'}><header><h2 className="text-2xl font-black">{l('Export Center','مركز التصدير')}</h2><p className="text-sm text-[var(--ink-soft)]">{l('Generate secure, filter-aware Excel workbooks. Authorization is always recalculated on the server.','إنشاء ملفات Excel آمنة ومتوافقة مع عوامل التصفية. يعاد احتساب الصلاحيات دائماً على الخادم.')}</p></header>
  <div className="grid gap-3 rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-4 sm:grid-cols-2 xl:grid-cols-4">{manager&&<label className="text-sm">{l('Scope','النطاق')}<select className="input mt-1 w-full" value={scope} onChange={e=>setScope(e.target.value)}><option value="ALL_DESCENDANTS">{l('All Descendants','جميع المرؤوسين')}</option><option value="DIRECT_REPORTS">{l('Direct Reports','المرؤوسون المباشرون')}</option></select></label>}<label className="text-sm">{l('From / compliance date','من / تاريخ الالتزام')}<input className="input mt-1 w-full" type="date" value={startDate} onChange={e=>setStartDate(e.target.value)}/></label><label className="text-sm">{l('To','إلى')}<input className="input mt-1 w-full" type="date" value={endDate} onChange={e=>setEndDate(e.target.value)}/></label><label className="text-sm">{l('Week start (Saturday)','بداية الأسبوع (السبت)')}<input className="input mt-1 w-full" type="date" value={weekStart} onChange={e=>setWeekStart(e.target.value)}/></label><label className="text-sm">{l('Month','الشهر')}<input className="input mt-1 w-full" type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><label className="text-sm">{l('Report type','نوع التقرير')}<select className="input mt-1 w-full" value={reportType} onChange={e=>setReportType(e.target.value)}>{['all','hospital','pharmacy','doctor','branch','availability','event','training','specialTask'].map(x=><option key={x} value={x}>{x}</option>)}</select></label>{manager&&<label className="text-sm">{l('Compliance type','نوع الالتزام')}<select className="input mt-1 w-full" value={complianceType} onChange={e=>setComplianceType(e.target.value)}><option value="DAILY_REPORT">{l('Daily Reports','التقارير اليومية')}</option><option value="WEEKLY_PLAN">{l('Weekly Plans','الخطط الأسبوعية')}</option><option value="MONTHLY_PRODUCT">{l('Monthly Product Analysis','تحليل المنتجات الشهري')}</option></select></label>}{manager&&<label className="text-sm">{l('Representative (optional)','المندوب (اختياري)')}<select className="input mt-1 w-full" value={repId} onChange={e=>setRepId(e.target.value)}><option value="">{l('All authorized','كل المصرح بهم')}</option>{reps.map(rep=><option key={rep.id} value={rep.id}>{rep.name}</option>)}</select></label>}</div>
  {error&&<InlineAlert tone="error">{error}</InlineAlert>}<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{cards.map(card=><SectionCard key={card.key} title={card.title} description={card.desc} actions={<span className="text-[var(--gold-dark)]">{card.icon}</span>}><Button className="mt-4 w-full" disabled={Boolean(busy)||(manager&&card.key==='lists'&&!repId)} onClick={()=>void download(card.key,card.url)}><Download className="size-4"/>{busy===card.key?l('Generating…','جارٍ الإنشاء…'):l('Download Excel','تحميل Excel')}</Button></SectionCard>)}</div></div>
}
