'use client';
import { useEffect,useMemo,useState } from 'react';
import type { ManagerActivityRecord } from '@/types';
import { Button } from '@/components/ui/Button';
import { FormField } from '@/components/ui/FormField';
import { FormSection } from '@/components/ui/FormSection';
import { InlineAlert } from '@/components/ui/InlineAlert';
type Option={id:string;name:string;repId?:string;specialty?:string|null};
type Manual={name:string;hospitalType:string;area:string;address:string;specialty:string;distributor:string;products:Array<{productId:string;observation:string}>};
type Visit={period:'AM'|'PM';entryType:'HOSPITAL'|'DIRECT_DOCTOR'|'PHARMACY'|'DISTRIBUTION_BRANCH';hospitalId?:string;doctorId?:string;pharmacyId?:string;branchId?:string;manualData?:Manual;generalComment:string;doctors:Array<{doctorName:string;department:string;generalComment:string}>};
type Options={reps:Option[];hospitals:Option[];doctors:Option[];pharmacies:Option[];branches:Option[];products:Option[]};
const blank:Options={reps:[],hospitals:[],doctors:[],pharmacies:[],branches:[],products:[]};
const ACTS=['MEETING','TRAINING','EVENT','SALES_REVIEW_ADMIN','OTHERS'] as const;
export function ManagerActivityForm({currentUser,onSuccess,onError,onSubmitted,initialActivity,onCancelEdit}:{currentUser?:{name:string;username:string;positionCode?:string|null}|null;onSuccess?:(x:string)=>void;onError?:(x:string)=>void;onSubmitted?:()=>void;initialActivity?:ManagerActivityRecord|null;onCancelEdit?:()=>void}){
 const[options,setOptions]=useState<Options>(blank),[repId,setRepId]=useState(initialActivity?.reportContextType==='VACANT'?'__VACANT__':initialActivity?.selectedRepId||''),[date,setDate]=useState(initialActivity?.activityDate||new Date().toLocaleDateString('en-CA',{timeZone:'Africa/Cairo'})),[visits,setVisits]=useState<Visit[]>(initialActivity?.visits?.map(v=>({...v,generalComment:v.generalComment||'',doctors:v.doctors.map(d=>({doctorName:d.name,department:d.specialty||'',generalComment:d.generalComment||''}))})) as Visit[]||[]),[activities,setActivities]=useState<string[]>(initialActivity?.activities||[]),[salesDescription,setSalesDescription]=useState(initialActivity?.salesReviewDescription||''),[othersDescription,setOthersDescription]=useState(initialActivity?.othersDescription||''),[notes,setNotes]=useState(initialActivity?.notes||''),[saving,setSaving]=useState(false),[error,setError]=useState('');
 useEffect(()=>{fetch('/api/manager/activity-options').then(r=>r.json()).then(setOptions).catch(()=>setError('Unable to load authorized representatives'));},[]);
 const scoped=useMemo(()=>({hospitals:options.hospitals.filter(x=>x.repId===repId),doctors:options.doctors.filter(x=>x.repId===repId),pharmacies:options.pharmacies.filter(x=>x.repId===repId),branches:options.branches.filter(x=>x.repId===repId)}),[options,repId]);
 const vacant=repId==='__VACANT__';const add=(period:'AM'|'PM',entryType:Visit['entryType'])=>setVisits(v=>[...v,{period,entryType,generalComment:'',doctors:[],...(vacant?{manualData:{name:'',hospitalType:'',area:'',address:'',specialty:'',distributor:'',products:[]}}:{})}]);const update=(i:number,p:Partial<Visit>)=>setVisits(v=>v.map((x,n)=>n===i?{...x,...p}:x));
 async function submit(e:React.FormEvent){e.preventDefault();setSaving(true);setError('');try{const body={id:initialActivity?.id,reportContextType:vacant?'VACANT':'EMPLOYEE',selectedRepId:vacant?null:repId,activityType:'Visit',activityDate:date,activities,salesReviewDescription:salesDescription,othersDescription,visits,productIds:[],notes};const r=await fetch(initialActivity?`/api/manager/activities/${initialActivity.id}`:'/api/manager/activities',{method:initialActivity?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.message);onSuccess?.('Manager daily report saved');onSubmitted?.();}catch(e){const m=e instanceof Error?e.message:'Unable to save report';setError(m);onError?.(m)}finally{setSaving(false)}}
 const manualField=(v:Visit,i:number,key:keyof Omit<Manual,'products'>,label:string)=><FormField label={label} value={String(v.manualData?.[key]||'')} onChange={value=>update(i,{manualData:{...v.manualData!,[key]:value}})} required={key==='name'}/>;
 return <form onSubmit={submit} className="space-y-5">
  <h2 className="text-xl font-black">Manager Daily Report — AM / PM</h2><p className="text-sm text-[var(--ink-soft)]">{currentUser?.name||currentUser?.username}</p>{error&&<InlineAlert tone="error">{error}</InlineAlert>}
  <FormSection title="Report context"><label className="sm:col-span-2">Supervised Medical Representative<select required className="input mt-1 w-full" value={repId} onChange={e=>{setRepId(e.target.value);setVisits([])}}><option value="">Select an authorized MR first</option>{options.reps.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}<option value="__VACANT__">Vacant</option></select></label><FormField label="Report date" type="date" value={date} onChange={setDate} required/></FormSection>
  {(['AM','PM'] as const).map(period=><FormSection key={period} title={`${period} visits`}><div className="sm:col-span-2 space-y-3">{visits.map((v,i)=>v.period===period&&<div key={i} className="space-y-2 rounded-xl border border-[var(--line)] p-3"><div className="flex justify-between"><b>{v.entryType.replaceAll('_',' ')}</b><Button type="button" size="sm" variant="danger" onClick={()=>setVisits(x=>x.filter((_,n)=>n!==i))}>Remove</Button></div>
   {vacant?<div className="grid gap-2 sm:grid-cols-2">{manualField(v,i,'name',`${v.entryType.replaceAll('_',' ')} name`)}{v.entryType==='HOSPITAL'&&manualField(v,i,'hospitalType','Hospital type')}{v.entryType==='DIRECT_DOCTOR'&&manualField(v,i,'specialty','Specialty')}{v.entryType==='PHARMACY'&&manualField(v,i,'distributor','Distributor dealt with')}{manualField(v,i,'area','Area')}{manualField(v,i,'address','Address')}</div>:<>{v.entryType==='HOSPITAL'&&<select required className="input w-full" value={v.hospitalId||''} onChange={e=>update(i,{hospitalId:e.target.value})}><option value="">Hospital from selected MR list</option>{scoped.hospitals.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>}{v.entryType==='DIRECT_DOCTOR'&&<select required className="input w-full" value={v.doctorId||''} onChange={e=>update(i,{doctorId:e.target.value})}><option value="">Doctor from selected MR list</option>{scoped.doctors.map(x=><option key={x.id} value={x.id}>{x.name} · {x.specialty}</option>)}</select>}{v.entryType==='PHARMACY'&&<select required className="input w-full" value={v.pharmacyId||''} onChange={e=>update(i,{pharmacyId:e.target.value})}><option value="">Pharmacy from selected MR list</option>{scoped.pharmacies.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>}{v.entryType==='DISTRIBUTION_BRANCH'&&<select required className="input w-full" value={v.branchId||''} onChange={e=>update(i,{branchId:e.target.value})}><option value="">Distribution branch from selected MR list</option>{scoped.branches.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>}</>}
   {v.entryType==='HOSPITAL'&&<>{v.doctors.map((d,j)=><div className="grid gap-2 sm:grid-cols-4" key={j}><FormField label="Doctor visited (manual)" value={d.doctorName} onChange={value=>update(i,{doctors:v.doctors.map((x,n)=>n===j?{...x,doctorName:value}:x)})} required/><FormField label="Department" value={d.department} onChange={value=>update(i,{doctors:v.doctors.map((x,n)=>n===j?{...x,department:value}:x)})}/><FormField label="Comment" value={d.generalComment} onChange={value=>update(i,{doctors:v.doctors.map((x,n)=>n===j?{...x,generalComment:value}:x)})}/><Button type="button" variant="danger" onClick={()=>update(i,{doctors:v.doctors.filter((_,n)=>n!==j)})}>Remove doctor</Button></div>)}{currentUser?.positionCode!=='BUM'&&<Button type="button" variant="secondary" onClick={()=>update(i,{doctors:[...v.doctors,{doctorName:'',department:'',generalComment:''}]})}>Add doctor visited</Button>}</>}
   {vacant&&v.entryType==='DISTRIBUTION_BRANCH'&&<div className="space-y-2"><b className="text-sm">Distributed products and observations</b>{options.products.filter(p=>['Nitrong','Danasetron','Beconeurin','Levosimendan Sunny'].includes(p.name)).map(p=><label className="grid grid-cols-[auto_1fr] gap-2" key={p.id}><input type="checkbox" checked={v.manualData!.products.some(x=>x.productId===p.id)} onChange={e=>update(i,{manualData:{...v.manualData!,products:e.target.checked?[...v.manualData!.products,{productId:p.id,observation:''}]:v.manualData!.products.filter(x=>x.productId!==p.id)}})}/><span>{p.name}</span>{v.manualData!.products.some(x=>x.productId===p.id)&&<textarea className="input col-start-2" placeholder="Product observation" value={v.manualData!.products.find(x=>x.productId===p.id)?.observation||''} onChange={e=>update(i,{manualData:{...v.manualData!,products:v.manualData!.products.map(x=>x.productId===p.id?{...x,observation:e.target.value}:x)}})}/>}</label>)}</div>}
   <FormField label="Visit comment / notes" value={v.generalComment} onChange={value=>update(i,{generalComment:value})} multiline/></div>)}<div className="flex flex-wrap gap-2">{(['HOSPITAL','DIRECT_DOCTOR','PHARMACY','DISTRIBUTION_BRANCH'] as const).map(t=><Button key={t} type="button" variant="secondary" disabled={!repId} onClick={()=>add(period,t)}>Add {t.replaceAll('_',' ').toLowerCase()}</Button>)}</div></div></FormSection>)}
  <FormSection title="Activities (multiple selection)"><div className="sm:col-span-2 flex flex-wrap gap-3">{ACTS.map(a=><label key={a}><input type="checkbox" checked={activities.includes(a)} onChange={e=>setActivities(x=>e.target.checked?[...x,a]:x.filter(v=>v!==a))}/> {a==='SALES_REVIEW_ADMIN'?'Sales Review / Admin Work':a[0]+a.slice(1).toLowerCase()}</label>)}</div>{activities.includes('SALES_REVIEW_ADMIN')&&<FormField label="Sales Review / Admin Work description" value={salesDescription} onChange={setSalesDescription} required multiline/>}{activities.includes('OTHERS')&&<FormField label="Others description" value={othersDescription} onChange={setOthersDescription} required multiline/>}<FormField label="Comments" value={notes} onChange={setNotes} multiline/></FormSection><div className="flex justify-end gap-2">{initialActivity&&<Button type="button" variant="secondary" onClick={onCancelEdit}>Cancel</Button>}<Button type="submit" disabled={!repId} isLoading={saving}>Submit daily report</Button></div>
 </form>;
}
