import * as dotenv from 'dotenv';dotenv.config({path:'.env.local'});
import {client} from '../src/lib/db';
import {computeTransitiveClosure} from '../src/lib/services/organizationService';
async function add(table:string,name:string,definition:string){const cols=await client.execute(`PRAGMA table_info(${table})`) as Array<{name:string}>;if(!cols.some(c=>c.name===name))await client.execute(`ALTER TABLE ${table} ADD COLUMN ${name} ${definition}`)}
async function counts(){const names=['users','representatives','organization_relationships','hierarchy_paths','weekly_plans','manager_weekly_plans','manager_activities','hospital_visits','doctor_visits','product_availabilities'];return Object.fromEntries(await Promise.all(names.map(async n=>[n,Number((await client.execute(`SELECT COUNT(*) count FROM ${n}`) as Array<{count:number}>)[0]?.count||0)])))}
async function main(){const before=await counts();await add('weekly_plans','structured_plan','TEXT');await add('manager_weekly_plans','selected_rep_id','TEXT REFERENCES representatives(id) ON DELETE RESTRICT');await add('manager_weekly_plans','structured_plan','TEXT');await add('manager_activities','selected_rep_id','TEXT REFERENCES representatives(id) ON DELETE RESTRICT');await add('manager_activities','activity_selections','TEXT');await add('manager_activity_entries','pharmacy_id','TEXT REFERENCES pharmacies(id) ON DELETE RESTRICT');await add('manager_activity_entries','branch_id','TEXT REFERENCES distribution_branches(id) ON DELETE RESTRICT');
 await client.execute('CREATE TABLE IF NOT EXISTS manager_activity_extended_entries (id TEXT PRIMARY KEY NOT NULL,activity_id TEXT NOT NULL REFERENCES manager_activities(id) ON DELETE CASCADE,period TEXT NOT NULL CHECK(period IN (\'AM\',\'PM\')),entry_type TEXT NOT NULL CHECK(entry_type IN (\'PHARMACY\',\'DISTRIBUTION_BRANCH\')),pharmacy_id TEXT REFERENCES pharmacies(id) ON DELETE RESTRICT,branch_id TEXT REFERENCES distribution_branches(id) ON DELETE RESTRICT,name_snapshot TEXT NOT NULL,general_comment TEXT,display_order INTEGER NOT NULL DEFAULT 0)');await client.execute('CREATE INDEX IF NOT EXISTS idx_mgr_extended_activity ON manager_activity_extended_entries(activity_id)');await client.execute('CREATE INDEX IF NOT EXISTS idx_mgr_plans_selected_rep ON manager_weekly_plans(selected_rep_id)');await client.execute('CREATE INDEX IF NOT EXISTS idx_mgr_activities_selected_rep ON manager_activities(selected_rep_id)');await client.execute('DROP INDEX IF EXISTS idx_mgr_weekly_plans_user_week');await client.execute('CREATE UNIQUE INDEX IF NOT EXISTS idx_mgr_weekly_plans_user_rep_week ON manager_weekly_plans(user_id,selected_rep_id,start_date)');
 const people=await client.execute("SELECT id,name,position_code FROM users WHERE lower(trim(name)) IN ('rafik maged','osama bert','michael antonyo')") as Array<{id:string;name:string;position_code:string}>;const find=(name:string)=>people.find(p=>p.name.trim().toLowerCase()===name);const rafik=find('rafik maged'),osama=find('osama bert');if(!rafik||!osama||rafik.position_code!=='DM'||osama.position_code!=='BUM')throw new Error('Canonical Rafik Maged DM / Osama Bert BUM records were not found uniquely');
 await client.execute('UPDATE organization_relationships SET is_active=0 WHERE subordinate_user_id=? AND manager_user_id<>?',[rafik.id,osama.id]);const existing=await client.execute('SELECT id FROM organization_relationships WHERE subordinate_user_id=? AND manager_user_id=? AND relationship_type=\'DIRECT\'',[rafik.id,osama.id]) as Array<{id:string}>;if(existing.length)await client.execute('UPDATE organization_relationships SET is_active=1,source_position=\'DM\',manager_position=\'BUM\',source_metadata=? WHERE id=?',[JSON.stringify({task:'TASK_4',authoritativeOverride:true}),existing[0].id]);else await client.execute('INSERT INTO organization_relationships(id,subordinate_user_id,manager_user_id,relationship_type,source_position,manager_position,is_active,source_metadata,created_at) VALUES(?,?,?,\'DIRECT\',\'DM\',\'BUM\',1,?,?)',[crypto.randomUUID(),rafik.id,osama.id,JSON.stringify({task:'TASK_4',authoritativeOverride:true}),Date.now()]);
 const[rels,userRows,assignments]=await Promise.all([client.execute('SELECT subordinate_user_id subordinateUserId,manager_user_id managerUserId,manager_position managerPosition,subordinate_assignment_id subordinateAssignmentId FROM organization_relationships WHERE is_active=1') as Promise<Array<{subordinateUserId:string;managerUserId:string;managerPosition:string;subordinateAssignmentId:string|null}>>,client.execute('SELECT id,position_code positionCode FROM users') as Promise<Array<{id:string;positionCode:string}>>,client.execute('SELECT id,user_id userId FROM sales_assignments WHERE is_active=1') as Promise<Array<{id:string;userId:string}>>]);const positions=new Map(userRows.map(u=>[u.id,u.positionCode]));const byUser=new Map<string,Array<{id:string}>>();for(const a of assignments)byUser.set(a.userId,[...(byUser.get(a.userId)||[]),{id:a.id}]);const paths=computeTransitiveClosure(rels,positions,byUser);await client.execute('DELETE FROM hierarchy_paths');for(const p of paths)await client.execute('INSERT INTO hierarchy_paths(id,source_assignment_id,source_user_id,ancestor_user_id,ancestor_position,depth,created_at) VALUES(?,?,?,?,?,?,?)',[p.id,p.sourceAssignmentId,p.sourceUserId,p.ancestorUserId,p.ancestorPosition,p.depth,Date.now()]);
 const after=await counts();console.log(JSON.stringify({status:'Task 4 migration complete',recoveryNote:'Create a Cloudflare D1 Time Travel bookmark immediately before running in Production.',rafikUserId:rafik.id,osamaUserId:osama.id,before,after},null,2));}
main().catch(e=>{console.error(e);process.exit(1)});
