import { asc, eq, inArray, like, or, sql } from 'drizzle-orm';
import type { UserSessionPayload } from '@/lib/auth';
import { AppError } from '@/lib/errors';
import { db, areas, hierarchyPaths, organizationRelationships, positions, productAvailabilities, products, representatives, salesAssignments, users, visitObjectives } from '@/lib/db';
import { assertAdminActor, recordAdminAudit } from './adminService';
import { computeTransitiveClosure, validateHierarchyAcyclicity } from './organizationService';

const POSITION_CODES = new Set(['MR','DM','AM','OM','BUM','PM','MM','SMD']);
type PageInput={search?:string;page?:number;pageSize?:number};
const pageValues=(input:PageInput)=>({page:Math.max(1,input.page??1),pageSize:Math.min(100,Math.max(10,input.pageSize??20))});

async function rebuildHierarchyPaths() {
  const [relationships, userRows, assignments] = await Promise.all([
    db.select().from(organizationRelationships).where(eq(organizationRelationships.isActive,true)).all(),
    db.select({id:users.id,positionCode:users.positionCode}).from(users).all(),
    db.select({id:salesAssignments.id,userId:salesAssignments.userId}).from(salesAssignments).where(eq(salesAssignments.isActive,true)).all(),
  ]);
  const positionMap=new Map(userRows.map(row=>[row.id,row.positionCode??'']));
  const assignmentsByUser=new Map<string,Array<{id:string}>>();
  for(const assignment of assignments) assignmentsByUser.set(assignment.userId,[...(assignmentsByUser.get(assignment.userId)??[]),{id:assignment.id}]);
  const paths=computeTransitiveClosure(relationships,positionMap,assignmentsByUser);
  if(paths.length) await db.batch([db.delete(hierarchyPaths),db.insert(hierarchyPaths).values(paths)]);
  else await db.delete(hierarchyPaths);
  return paths.length;
}

export function validateRelationshipGraph(edges:Array<{subordinateUserId:string;managerUserId:string}>,candidate:{subordinateUserId:string;managerUserId:string}) {
  if(candidate.subordinateUserId===candidate.managerUserId) throw new AppError('Self-management is not allowed',400);
  if(edges.some(edge=>edge.subordinateUserId===candidate.subordinateUserId&&edge.managerUserId===candidate.managerUserId)) throw new AppError('Relationship already exists',409);
  const validation=validateHierarchyAcyclicity([...edges,candidate]);
  if(!validation.isValid) throw new AppError('Relationship would create a hierarchy cycle',409,{cyclePath:validation.cyclePath});
}

export async function getOrganizationAdmin(admin:UserSessionPayload,input:PageInput={}) { assertAdminActor(admin);const{page,pageSize}=pageValues(input);const term=input.search?.trim();const where=term?or(like(users.name,`%${term}%`),like(users.username,`%${term}%`),like(users.positionCode,`%${term}%`)):undefined;const[employeeRows,totalRow,relationships,assignments,paths]=await Promise.all([db.select({id:users.id,name:users.name,username:users.username,positionCode:users.positionCode,systemRole:users.systemRole,isActive:users.isActive}).from(users).where(where).orderBy(asc(users.name)).limit(pageSize).offset((page-1)*pageSize).all(),db.select({count:sql<number>`count(*)`}).from(users).where(where).get(),db.select().from(organizationRelationships).where(eq(organizationRelationships.isActive,true)).all(),db.select().from(salesAssignments).where(eq(salesAssignments.isActive,true)).all(),db.select().from(hierarchyPaths).all()]);const nameMap=new Map((await db.select({id:users.id,name:users.name,positionCode:users.positionCode}).from(users).all()).map(row=>[row.id,row]));return{employees:employeeRows.map(user=>({...user,assignments:assignments.filter(a=>a.userId===user.id),directManagers:relationships.filter(r=>r.subordinateUserId===user.id).map(r=>nameMap.get(r.managerUserId)).filter(Boolean),directReports:relationships.filter(r=>r.managerUserId===user.id).map(r=>nameMap.get(r.subordinateUserId)).filter(Boolean),ancestors:[...new Map(paths.filter(p=>p.sourceUserId===user.id).map(p=>[p.ancestorUserId,nameMap.get(p.ancestorUserId)])).values()].filter(Boolean),descendants:[...new Map(paths.filter(p=>p.ancestorUserId===user.id).map(p=>[p.sourceUserId,nameMap.get(p.sourceUserId)])).values()].filter(Boolean)})),relationships:relationships.map(r=>({...r,subordinate:nameMap.get(r.subordinateUserId),manager:nameMap.get(r.managerUserId)})),total:totalRow?.count??0,page,pageSize};}

export async function addHierarchyRelationship(admin:UserSessionPayload,input:{subordinateUserId:string;managerUserId:string}){assertAdminActor(admin);const[userRows,edges]=await Promise.all([db.select({id:users.id,positionCode:users.positionCode,isActive:users.isActive}).from(users).where(inArray(users.id,[input.subordinateUserId,input.managerUserId])).all(),db.select({subordinateUserId:organizationRelationships.subordinateUserId,managerUserId:organizationRelationships.managerUserId}).from(organizationRelationships).where(eq(organizationRelationships.isActive,true)).all()]);if(userRows.length!==2||userRows.some(user=>!user.isActive))throw new AppError('Both employees must exist and be active',400);const subordinate=userRows.find(u=>u.id===input.subordinateUserId)!;const manager=userRows.find(u=>u.id===input.managerUserId)!;if(!POSITION_CODES.has(subordinate.positionCode??'')||!POSITION_CODES.has(manager.positionCode??'')||manager.positionCode==='MR')throw new AppError('Invalid structural positions for manager relationship',400);validateRelationshipGraph(edges,input);const id=crypto.randomUUID();await db.insert(organizationRelationships).values({id,...input,relationshipType:'DIRECT',sourcePosition:subordinate.positionCode!,managerPosition:manager.positionCode!,isActive:true,sourceMetadata:JSON.stringify({createdBy:'ADMIN_UI'})});const pathCount=await rebuildHierarchyPaths();await recordAdminAudit(admin.id,'HIERARCHY_RELATIONSHIP_ADDED','RELATIONSHIP',id,{...input,sourcePosition:subordinate.positionCode,managerPosition:manager.positionCode,pathCount});return{id,pathCount};}
export async function previewHierarchyRemoval(admin:UserSessionPayload,id:string){assertAdminActor(admin);const relationship=await db.select().from(organizationRelationships).where(eq(organizationRelationships.id,id)).get();if(!relationship)throw new AppError('Relationship not found',404);const affected=await db.select({sourceUserId:hierarchyPaths.sourceUserId}).from(hierarchyPaths).where(eq(hierarchyPaths.ancestorUserId,relationship.managerUserId)).all();return{relationship,affectedDescendants:new Set(affected.map(row=>row.sourceUserId)).size};}
export async function removeHierarchyRelationship(admin:UserSessionPayload,id:string){const preview=await previewHierarchyRemoval(admin,id);await db.delete(organizationRelationships).where(eq(organizationRelationships.id,id));const pathCount=await rebuildHierarchyPaths();await recordAdminAudit(admin.id,'HIERARCHY_RELATIONSHIP_REMOVED','RELATIONSHIP',id,{subordinateUserId:preview.relationship.subordinateUserId,managerUserId:preview.relationship.managerUserId,affectedDescendants:preview.affectedDescendants,pathCount});return{success:true,pathCount};}

export async function listAssignmentsAdmin(admin:UserSessionPayload,input:PageInput={}){assertAdminActor(admin);const{page,pageSize}=pageValues(input);const term=input.search?.trim();const where=term?or(like(salesAssignments.territoryName,`%${term}%`),like(salesAssignments.titleRaw,`%${term}%`)):undefined;const[rows,totalRow,userRows,areaRows,repRows,activeLinks]=await Promise.all([db.select().from(salesAssignments).where(where).orderBy(asc(salesAssignments.territoryName)).limit(pageSize).offset((page-1)*pageSize).all(),db.select({count:sql<number>`count(*)`}).from(salesAssignments).where(where).get(),db.select({id:users.id,name:users.name,positionCode:users.positionCode,isActive:users.isActive}).from(users).all(),db.select().from(areas).all(),db.select().from(representatives).all(),db.select({repId:salesAssignments.repId}).from(salesAssignments).where(eq(salesAssignments.isActive,true)).all()]);const linkedRepIds=new Set(activeLinks.map(row=>row.repId).filter(Boolean));const vacant=repRows.filter(rep=>!linkedRepIds.has(rep.id)).map(rep=>({id:`vacant:${rep.id}`,territoryName:rep.area,titleRaw:'MR',assignmentType:'VACANT',isActive:rep.isActive,userId:null,employee:null,representative:rep,area:null}));const userMap=new Map(userRows.map(row=>[row.id,row]));const areaMap=new Map(areaRows.map(row=>[row.id,row]));const repMap=new Map(repRows.map(row=>[row.id,row]));return{assignments:rows.map(row=>({...row,employee:userMap.get(row.userId),area:row.areaId?areaMap.get(row.areaId):null,representative:row.repId?repMap.get(row.repId):null})),vacant,total:totalRow?.count??0,page,pageSize,options:{users:userRows.filter(u=>u.isActive),areas:areaRows.filter(a=>a.isActive),representatives:repRows.filter(r=>r.isActive)}};}
export async function createAssignmentAdmin(admin:UserSessionPayload,input:typeof salesAssignments.$inferInsert){assertAdminActor(admin);const user=await db.select().from(users).where(eq(users.id,input.userId!)).get();if(!user||!user.isActive)throw new AppError('Assigned employee must exist and be active',400);if(input.assignmentType==='PERSONAL_MR'&&user.role!=='MANAGER')throw new AppError('PERSONAL_MR is only valid for a manager account',400);const id=crypto.randomUUID();await db.insert(salesAssignments).values({...input,id});await rebuildHierarchyPaths();await recordAdminAudit(admin.id,'ASSIGNMENT_CREATED','ASSIGNMENT',id,{userId:user.id,assignmentType:input.assignmentType,territoryName:input.territoryName});return{id};}
export async function updateAssignmentAdmin(admin:UserSessionPayload,id:string,input:Partial<typeof salesAssignments.$inferInsert>){assertAdminActor(admin);const existing=await db.select().from(salesAssignments).where(eq(salesAssignments.id,id)).get();if(!existing)throw new AppError('Assignment not found',404);await db.update(salesAssignments).set({...input,updatedAt:new Date()}).where(eq(salesAssignments.id,id));await rebuildHierarchyPaths();await recordAdminAudit(admin.id,input.isActive===false?'ASSIGNMENT_DEACTIVATED':'ASSIGNMENT_CHANGED','ASSIGNMENT',id,{fields:Object.keys(input),territoryName:input.territoryName??existing.territoryName});return{success:true};}

async function listCatalog<T>(admin:UserSessionPayload,input:PageInput,query:()=>Promise<T[]>,count:()=>Promise<{count:number}|undefined>){assertAdminActor(admin);const{page,pageSize}=pageValues(input);return{rows:await query(),total:(await count())?.count??0,page,pageSize};}
export async function listAreasAdmin(admin:UserSessionPayload,input:PageInput={}){const{page,pageSize}=pageValues(input);const term=input.search?.trim();const where=term?like(areas.name,`%${term}%`):undefined;const result=await listCatalog(admin,input,()=>db.select().from(areas).where(where).orderBy(asc(areas.name)).limit(pageSize).offset((page-1)*pageSize).all(),()=>db.select({count:sql<number>`count(*)`}).from(areas).where(where).get());const links=await db.select({areaId:salesAssignments.areaId}).from(salesAssignments).all();return{...result,rows:result.rows.map(row=>({...row,linkedAssignments:links.filter(link=>link.areaId===row.id).length}))};}
export async function createAreaAdmin(admin:UserSessionPayload,input:typeof areas.$inferInsert){assertAdminActor(admin);const id=crypto.randomUUID();await db.insert(areas).values({...input,id});await recordAdminAudit(admin.id,'AREA_CREATED','AREA',id,{name:input.name});return{id};}
export async function updateAreaAdmin(admin:UserSessionPayload,id:string,input:Partial<typeof areas.$inferInsert>){assertAdminActor(admin);await db.update(areas).set({...input,updatedAt:new Date()}).where(eq(areas.id,id));await recordAdminAudit(admin.id,input.isActive===false?'AREA_DEACTIVATED':'AREA_CHANGED','AREA',id,{fields:Object.keys(input)});return{success:true};}
export async function listProductsAdmin(admin:UserSessionPayload,input:PageInput={}){const{page,pageSize}=pageValues(input);const term=input.search?.trim();const where=term?or(like(products.name,`%${term}%`),like(products.code,`%${term}%`)):undefined;const result=await listCatalog(admin,input,()=>db.select().from(products).where(where).orderBy(asc(products.name)).limit(pageSize).offset((page-1)*pageSize).all(),()=>db.select({count:sql<number>`count(*)`}).from(products).where(where).get());const usage=await db.select({productId:productAvailabilities.productId}).from(productAvailabilities).all();return{...result,rows:result.rows.map(row=>({...row,usageCount:usage.filter(item=>item.productId===row.id).length}))};}
export async function createProductAdmin(admin:UserSessionPayload,input:typeof products.$inferInsert){assertAdminActor(admin);const id=crypto.randomUUID();await db.insert(products).values({...input,id});await recordAdminAudit(admin.id,'PRODUCT_CREATED','PRODUCT',id,{name:input.name,code:input.code});return{id};}
export async function updateProductAdmin(admin:UserSessionPayload,id:string,input:Partial<typeof products.$inferInsert>){assertAdminActor(admin);await db.update(products).set(input).where(eq(products.id,id));await recordAdminAudit(admin.id,input.isActive===false?'PRODUCT_DEACTIVATED':'PRODUCT_CHANGED','PRODUCT',id,{fields:Object.keys(input)});return{success:true};}
export async function listObjectivesAdmin(admin:UserSessionPayload,input:PageInput={}){const{page,pageSize}=pageValues(input);const term=input.search?.trim();const where=term?or(like(visitObjectives.nameEn,`%${term}%`),like(visitObjectives.nameAr,`%${term}%`),like(visitObjectives.objectiveCode,`%${term}%`)):undefined;return listCatalog(admin,input,()=>db.select().from(visitObjectives).where(where).orderBy(asc(visitObjectives.displayOrder)).limit(pageSize).offset((page-1)*pageSize).all(),()=>db.select({count:sql<number>`count(*)`}).from(visitObjectives).where(where).get());}
export async function createObjectiveAdmin(admin:UserSessionPayload,input:typeof visitObjectives.$inferInsert){assertAdminActor(admin);const id=crypto.randomUUID();await db.insert(visitObjectives).values({...input,id});await recordAdminAudit(admin.id,'VISIT_OBJECTIVE_CREATED','VISIT_OBJECTIVE',id,{positionCode:input.positionCode,objectiveCode:input.objectiveCode});return{id};}
export async function updateObjectiveAdmin(admin:UserSessionPayload,id:string,input:Partial<typeof visitObjectives.$inferInsert>){assertAdminActor(admin);await db.update(visitObjectives).set({...input,updatedAt:new Date()}).where(eq(visitObjectives.id,id));await recordAdminAudit(admin.id,input.isActive===false?'VISIT_OBJECTIVE_DEACTIVATED':'VISIT_OBJECTIVE_CHANGED','VISIT_OBJECTIVE',id,{fields:Object.keys(input)});return{success:true};}
export async function listRepresentativesAdmin(admin:UserSessionPayload,input:PageInput={}){assertAdminActor(admin);const{page,pageSize}=pageValues(input);const term=input.search?.trim();const where=term?or(like(representatives.name,`%${term}%`),like(representatives.area,`%${term}%`)):undefined;const[rows,totalRow,userRows,assignments]=await Promise.all([db.select().from(representatives).where(where).orderBy(asc(representatives.name)).limit(pageSize).offset((page-1)*pageSize).all(),db.select({count:sql<number>`count(*)`}).from(representatives).where(where).get(),db.select({id:users.id,name:users.name,repId:users.repId}).from(users).all(),db.select().from(salesAssignments).all()]);return{representatives:rows.map(rep=>({...rep,employee:userRows.find(user=>user.repId===rep.id)??null,assignments:assignments.filter(a=>a.repId===rep.id),vacant:!userRows.some(user=>user.repId===rep.id)&&!assignments.some(a=>a.repId===rep.id&&a.isActive)})),total:totalRow?.count??0,page,pageSize};}
export async function createRepresentativeAdmin(admin:UserSessionPayload,input:typeof representatives.$inferInsert){assertAdminActor(admin);const id=crypto.randomUUID();await db.insert(representatives).values({...input,id});await recordAdminAudit(admin.id,'REPRESENTATIVE_PROFILE_CREATED','REPRESENTATIVE',id,{name:input.name,area:input.area,vacant:true});return{id};}
export async function updateRepresentativeAdmin(admin:UserSessionPayload,id:string,input:Partial<typeof representatives.$inferInsert>){assertAdminActor(admin);await db.update(representatives).set({...input,updatedAt:new Date()}).where(eq(representatives.id,id));await recordAdminAudit(admin.id,'REPRESENTATIVE_PROFILE_CHANGED','REPRESENTATIVE',id,{fields:Object.keys(input)});return{success:true};}
export async function getReferenceDataAdmin(admin:UserSessionPayload){assertAdminActor(admin);return{activityTypes:['Visit','Event','Training','Office Working','Others'],visitTypes:['Single','Double'],assignmentTypes:['PRIMARY_REP','PERSONAL_MR','TERRITORY_COVERAGE'],positionCodes:(await db.select().from(positions).orderBy(asc(positions.hierarchyLevel)).all()).map(position=>({...position,structuralCodeProtected:true})),specialties:{managedDataset:false,message:'Specialties are currently recorded on doctor profiles; no canonical specialty table exists.'}};}
