import { db, managerActivities, managerActivityEntries, managerActivityEntryDoctors, managerActivityProducts, users, hospitals, doctors, products } from '@/lib/db';
import { eq, and, desc, gte, lte, inArray } from 'drizzle-orm';
import { UserSessionPayload } from '@/lib/auth';
import { assertManagerSession, assertManagerOwner } from '@/lib/authPolicy';
import { ManagerActivitySchema, ManagerActivityFiltersSchema } from '@/lib/validation';
import { ManagerActivityRecord } from '@/types';
import { hierarchyService, HierarchyScopeMode } from './hierarchyService';
import { AppError } from '@/lib/errors';

async function scopedOptions(session: UserSessionPayload) {
  const repIds = await hierarchyService.getScopedRepIds(session);
  const [hospitalRows, doctorRows, productRows] = await Promise.all([
    repIds.length ? db.select({ id:hospitals.id, name:hospitals.name }).from(hospitals).where(and(inArray(hospitals.repId, repIds), eq(hospitals.isActive, true))).all() : [],
    repIds.length ? db.select({ id:doctors.id, name:doctors.name, specialty:doctors.specialty }).from(doctors).where(and(inArray(doctors.repId, repIds), eq(doctors.isActive, true))).all() : [],
    db.select({ id:products.id, name:products.name }).from(products).where(eq(products.isActive, true)).all(),
  ]);
  return { hospitals: hospitalRows.map((row)=>({...row,specialty:null as string|null})), doctors: doctorRows, products: productRows };
}
export async function getManagerActivityOptions(session: UserSessionPayload | null) { assertManagerSession(session); return scopedOptions(session); }

export async function saveManagerActivity(session: UserSessionPayload | null, rawInput: unknown): Promise<ManagerActivityRecord> {
  assertManagerSession(session); const parsed=ManagerActivitySchema.parse(rawInput); const options=await scopedOptions(session);
  const hospitalMap=new Map(options.hospitals.map(row=>[row.id,row]));const doctorMap=new Map(options.doctors.map(row=>[row.id,row]));const productMap=new Map(options.products.map(row=>[row.id,row]));
  for(const visit of parsed.visits){if(visit.hospitalId&&!hospitalMap.has(visit.hospitalId))throw new AppError('Hospital is outside your authorized hierarchy',403);if(visit.doctorId&&!doctorMap.has(visit.doctorId))throw new AppError('Doctor is outside your authorized hierarchy',403);for(const item of visit.doctors)if(!doctorMap.has(item.doctorId))throw new AppError('Doctor is outside your authorized hierarchy',403);}
  if(parsed.productIds.some(id=>!productMap.has(id)))throw new AppError('Invalid or inactive product',400);
  const now=new Date(),id=parsed.id??crypto.randomUUID();const parent={userId:session.id,activityType:parsed.activityType,activityDate:parsed.activityDate,visitType:parsed.activityType==='Visit'?parsed.visitType:null,accompaniedPerson:parsed.activityType==='Visit'&&parsed.visitType==='Double'?parsed.accompaniedPerson:null,generalComment:parsed.activityType==='Visit'?parsed.generalComment:null,eventName:parsed.activityType==='Event'?parsed.eventName:null,eventType:parsed.activityType==='Event'?parsed.eventType:null,location:parsed.activityType==='Event'?parsed.location:null,attendees:parsed.activityType==='Event'?parsed.attendees:null,budget:parsed.activityType==='Event'?parsed.budget:null,eventFeedback:parsed.activityType==='Event'?parsed.eventFeedback:null,trainingType:parsed.activityType==='Training'?parsed.trainingType:null,trainingTopic:parsed.activityType==='Training'?parsed.trainingTopic:null,trainingLocation:parsed.activityType==='Training'?parsed.trainingLocation:null,participants:parsed.activityType==='Training'?parsed.participants:null,workSummary:parsed.activityType==='Office Working'?parsed.workSummary:null,description:parsed.activityType==='Others'?parsed.description:null,notes:parsed.notes||null,updatedAt:now};
  if(parsed.id){const existing=await db.select().from(managerActivities).where(eq(managerActivities.id,id)).get();if(!existing)throw new AppError('Activity not found',404);assertManagerOwner(session,existing.userId);await db.batch([db.delete(managerActivityProducts).where(eq(managerActivityProducts.activityId,id)),db.delete(managerActivityEntries).where(eq(managerActivityEntries.activityId,id)),db.update(managerActivities).set(parent).where(and(eq(managerActivities.id,id),eq(managerActivities.userId,session.id)))]);}else await db.insert(managerActivities).values({id,...parent,submittedAt:now});
  const operations:unknown[]=[];
  parsed.visits.forEach((visit,index)=>{const entryId=crypto.randomUUID();const entity=visit.entryType==='HOSPITAL'?hospitalMap.get(visit.hospitalId!)!:doctorMap.get(visit.doctorId!)!;const specialty='specialty' in entity?entity.specialty:null;operations.push(db.insert(managerActivityEntries).values({id:entryId,activityId:id,period:visit.period,entryType:visit.entryType,hospitalId:visit.hospitalId??null,doctorId:visit.doctorId??null,nameSnapshot:entity.name,specialtySnapshot:specialty,generalComment:visit.generalComment||null,displayOrder:index}));visit.doctors.forEach((item,doctorIndex)=>{const doctor=doctorMap.get(item.doctorId)!;operations.push(db.insert(managerActivityEntryDoctors).values({id:crypto.randomUUID(),entryId,doctorId:doctor.id,nameSnapshot:doctor.name,specialtySnapshot:doctor.specialty,generalComment:item.generalComment||null,displayOrder:doctorIndex}));});});
  parsed.productIds.forEach(productId=>{const product=productMap.get(productId)!;operations.push(db.insert(managerActivityProducts).values({activityId:id,productId,productNameSnapshot:product.name}));});if(operations.length)await db.batch(operations as never);
  return (await getManagerActivityById(session,id))!;
}

async function hydrate(row:typeof managerActivities.$inferSelect,userName?:string,userPosition?:string):Promise<ManagerActivityRecord>{const[entries,nested,productRows]=await Promise.all([db.select().from(managerActivityEntries).where(eq(managerActivityEntries.activityId,row.id)).all(),db.select({doctor:managerActivityEntryDoctors}).from(managerActivityEntryDoctors).innerJoin(managerActivityEntries,eq(managerActivityEntryDoctors.entryId,managerActivityEntries.id)).where(eq(managerActivityEntries.activityId,row.id)).all(),db.select().from(managerActivityProducts).where(eq(managerActivityProducts.activityId,row.id)).all()]);return{id:row.id,userId:row.userId,userName,userPosition,activityType:row.activityType,activityDate:row.activityDate,visitType:row.visitType??undefined,accompaniedPerson:row.accompaniedPerson??undefined,morningHospitalName:row.morningHospitalName??undefined,morningDoctorNames:row.morningDoctorNames??undefined,morningSpecialty:row.morningSpecialty??undefined,morningHospitalComment:row.morningHospitalComment??undefined,afternoonDoctorNames:row.afternoonDoctorNames??undefined,afternoonSpecialty:row.afternoonSpecialty??undefined,afternoonDoctorComment:row.afternoonDoctorComment??undefined,afternoonPharmacyName:row.afternoonPharmacyName??undefined,afternoonPharmacyComment:row.afternoonPharmacyComment??undefined,generalComment:row.generalComment??undefined,eventName:row.eventName??undefined,eventType:row.eventType??undefined,location:row.location??undefined,attendees:row.attendees??undefined,budget:row.budget??undefined,eventFeedback:row.eventFeedback??undefined,trainingType:row.trainingType??undefined,trainingTopic:row.trainingTopic??undefined,trainingLocation:row.trainingLocation??undefined,participants:row.participants??undefined,workSummary:row.workSummary??undefined,description:row.description??undefined,notes:row.notes??undefined,productsDiscussed:productRows.map(p=>({id:p.productId,name:p.productNameSnapshot})),visits:entries.sort((a,b)=>a.displayOrder-b.displayOrder).map(entry=>({id:entry.id,period:entry.period,entryType:entry.entryType,hospitalId:entry.hospitalId??undefined,doctorId:entry.doctorId??undefined,name:entry.nameSnapshot,specialty:entry.specialtySnapshot??undefined,generalComment:entry.generalComment??undefined,doctors:nested.filter(x=>x.doctor.entryId===entry.id).sort((a,b)=>a.doctor.displayOrder-b.doctor.displayOrder).map(({doctor})=>({id:doctor.id,doctorId:doctor.doctorId,name:doctor.nameSnapshot,specialty:doctor.specialtySnapshot??undefined,generalComment:doctor.generalComment??undefined}))})),submittedAt:row.submittedAt?new Date(row.submittedAt).toISOString():undefined,updatedAt:row.updatedAt?new Date(row.updatedAt).toISOString():undefined};}
export async function getManagerActivitiesForTeam(session:UserSessionPayload|null,filters:{startDate?:string;endDate?:string;activityType?:string;subordinateUserId?:string;positionCode?:string;scopeMode?:HierarchyScopeMode}={}):Promise<ManagerActivityRecord[]>{assertManagerSession(session);let userIds=await hierarchyService.getScopedUserIds(session,filters.scopeMode);if(filters.subordinateUserId){if(!userIds.includes(filters.subordinateUserId))throw new AppError('Employee is outside your authorized hierarchy',403);userIds=[filters.subordinateUserId];}if(!userIds.length)return[];const conditions=[inArray(managerActivities.userId,userIds)];if(filters.startDate)conditions.push(gte(managerActivities.activityDate,filters.startDate));if(filters.endDate)conditions.push(lte(managerActivities.activityDate,filters.endDate));if(filters.activityType&&filters.activityType!=='All')conditions.push(eq(managerActivities.activityType,filters.activityType as ManagerActivityRecord['activityType']));if(filters.positionCode)conditions.push(eq(users.positionCode,filters.positionCode));const rows=await db.select({activity:managerActivities,userName:users.name,userPosition:users.positionCode}).from(managerActivities).innerJoin(users,eq(managerActivities.userId,users.id)).where(and(...conditions)).orderBy(desc(managerActivities.activityDate),desc(managerActivities.submittedAt)).all();return Promise.all(rows.map(r=>hydrate(r.activity,r.userName,r.userPosition??undefined)));}
export async function getManagerActivities(session:UserSessionPayload|null,filters:{startDate?:string;endDate?:string;activityType?:string}={}):Promise<ManagerActivityRecord[]>{assertManagerSession(session);filters=ManagerActivityFiltersSchema.parse(filters);const conditions=[eq(managerActivities.userId,session.id)];if(filters.startDate)conditions.push(gte(managerActivities.activityDate,filters.startDate));if(filters.endDate)conditions.push(lte(managerActivities.activityDate,filters.endDate));if(filters.activityType&&filters.activityType!=='All')conditions.push(eq(managerActivities.activityType,filters.activityType as ManagerActivityRecord['activityType']));const rows=await db.select().from(managerActivities).where(and(...conditions)).orderBy(desc(managerActivities.activityDate),desc(managerActivities.submittedAt)).all();return Promise.all(rows.map(r=>hydrate(r,session.name,session.positionCode??undefined)));}
export async function getManagerActivityById(session:UserSessionPayload|null,id:string):Promise<ManagerActivityRecord|null>{assertManagerSession(session);const row=await db.select().from(managerActivities).where(eq(managerActivities.id,id)).get();if(!row)return null;await hierarchyService.assertUserVisible(session,row.userId);const owner=await db.select({name:users.name,positionCode:users.positionCode}).from(users).where(eq(users.id,row.userId)).get();return hydrate(row,owner?.name,owner?.positionCode??undefined);}
export async function deleteManagerActivity(session:UserSessionPayload|null,id:string):Promise<boolean>{assertManagerSession(session);const existing=await db.select().from(managerActivities).where(eq(managerActivities.id,id)).get();if(!existing)return false;assertManagerOwner(session,existing.userId);await db.delete(managerActivities).where(and(eq(managerActivities.id,id),eq(managerActivities.userId,session.id))).run();return true;}
